# Generated by Django 2.2.7 on 2019-12-03 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20191203_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionrecord',
            name='is_done',
        ),
    ]
