# Generated by Django 2.2.7 on 2019-12-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_remove_sectionrecord_is_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionrecord',
            options={'verbose_name': '章节记录', 'verbose_name_plural': '章节记录'},
        ),
        migrations.AddField(
            model_name='wrongquestion',
            name='wrong_count',
            field=models.PositiveIntegerField(default=1, verbose_name='错误次数'),
        ),
    ]
