# Generated by Django 2.2.7 on 2019-11-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='章名称')),
                ('number', models.IntegerField(db_index=True, verbose_name='章序号')),
            ],
            options={
                'verbose_name': '章',
                'verbose_name_plural': '章',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='DayAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateField(auto_now_add=True, unique=True, verbose_name='创建时间')),
                ('analysis_file', models.CharField(max_length=100, verbose_name='笔记文件')),
            ],
            options={
                'verbose_name': '每日打卡',
                'verbose_name_plural': '每日打卡',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='试卷名称')),
                ('number', models.IntegerField(verbose_name='试卷编号')),
                ('exam_type', models.IntegerField(choices=[(0, '历年真题'), (1, '模拟题')], db_index=True, verbose_name='试卷类型')),
                ('exam_time', models.PositiveIntegerField(default=120, verbose_name='考试时间')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.PositiveIntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '判断题')], default=0)),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='题目')),
                ('stem', models.CharField(blank=True, db_index=True, max_length=200, null=True, verbose_name='题干')),
                ('answer', models.CharField(db_index=True, max_length=1, verbose_name='答案')),
                ('analysis', models.CharField(max_length=500, verbose_name='解析')),
                ('choice_a', models.CharField(max_length=100, verbose_name='选项A')),
                ('choice_b', models.CharField(max_length=100, verbose_name='选项B')),
                ('choice_c', models.CharField(max_length=100, verbose_name='选项C')),
                ('choice_d', models.CharField(max_length=100, verbose_name='选项D')),
                ('choice_e', models.CharField(max_length=100, verbose_name='选项E')),
                ('image', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片')),
                ('video', models.CharField(blank=True, max_length=100, null=True, verbose_name='视频')),
            ],
            options={
                'verbose_name': '题目库',
                'verbose_name_plural': '题目库',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='节名称')),
                ('number', models.IntegerField(db_index=True, verbose_name='节序号')),
                ('difficulty', models.PositiveIntegerField(choices=[(0, '简单'), (1, '中等'), (2, '困难')], verbose_name='难度')),
                ('is_keypoint', models.BooleanField(verbose_name='是否重点')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='examination.Chapter', verbose_name='所属章')),
            ],
            options={
                'verbose_name': '节',
                'verbose_name_plural': '节',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('number', models.PositiveIntegerField(verbose_name='序号')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Section')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('section', 'question')},
            },
        ),
        migrations.AddField(
            model_name='section',
            name='questions',
            field=models.ManyToManyField(through='examination.SectionQuestion', to='examination.Question', verbose_name='章节题目'),
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('number', models.PositiveIntegerField(verbose_name='序号')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Examination')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('examination', 'question')},
            },
        ),
        migrations.AddField(
            model_name='examination',
            name='questions',
            field=models.ManyToManyField(through='examination.ExamQuestion', to='examination.Question', verbose_name='试卷题目'),
        ),
        migrations.CreateModel(
            name='DayQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='序号')),
                ('day_attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.DayAttendance')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('question', 'day_attendance')},
            },
        ),
        migrations.AddField(
            model_name='dayattendance',
            name='questions',
            field=models.ManyToManyField(through='examination.DayQuestion', to='examination.Question', verbose_name='每日题目'),
        ),
    ]
