# Generated by Django 2.2.7 on 2019-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveIntegerField(choices=[(0, '单选题'), (1, '多选题'), (2, '判断题')], default=0, verbose_name='题目类型'),
        ),
    ]
