# Generated by Django 2.2.7 on 2019-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0002_auto_20191124_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=1, verbose_name='答案'),
        ),
    ]
