# Generated by Django 2.2.7 on 2019-11-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_auto_20191125_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='analysis',
            field=models.CharField(max_length=1000, verbose_name='解析'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.CharField(max_length=200, verbose_name='选项A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.CharField(max_length=200, verbose_name='选项B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.CharField(max_length=200, verbose_name='选项C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.CharField(max_length=200, verbose_name='选项D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_e',
            field=models.CharField(max_length=200, verbose_name='选项E'),
        ),
        migrations.AlterField(
            model_name='question',
            name='stem',
            field=models.CharField(blank=True, db_index=True, max_length=1000, null=True, verbose_name='题干'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(db_index=True, max_length=1000, verbose_name='题目'),
        ),
    ]
