# Generated by Django 2.2.7 on 2019-12-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_auto_20191128_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayquestion',
            options={'ordering': ['number'], 'verbose_name': '打卡题目关联', 'verbose_name_plural': '打卡题目关联'},
        ),
        migrations.AlterModelOptions(
            name='examquestion',
            options={'ordering': ['number'], 'verbose_name': '试卷题目关联', 'verbose_name_plural': '试卷题目关联'},
        ),
        migrations.AlterModelOptions(
            name='sectionquestion',
            options={'ordering': ['number'], 'verbose_name': '章节题目关联', 'verbose_name_plural': '章节题目关联'},
        ),
        migrations.AlterField(
            model_name='dayquestion',
            name='day_attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.DayAttendance', verbose_name='每日打卡'),
        ),
        migrations.AlterField(
            model_name='dayquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='examination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Examination', verbose_name='所属试卷'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Question', verbose_name='题目'),
        ),
        migrations.AlterField(
            model_name='sectionquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Section', verbose_name='所属章节'),
        ),
    ]
