# Generated by Django 2.2.7 on 2019-11-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191124_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default=0, max_length=100, verbose_name='头像'),
        ),
    ]
